#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $POSTGRES_API_USER with encrypted password '$POSTGRES_API_USER_PASSWORD';
  CREATE DATABASE hnk_prod;
  CREATE DATABASE hnk_dev;
  CREATE DATABASE hnk_test;
  GRANT ALL PRIVILEGES ON DATABASE hnk_prod TO $POSTGRES_API_USER;
  GRANT ALL PRIVILEGES ON DATABASE hnk_dev TO $POSTGRES_API_USER;
  GRANT ALL PRIVILEGES ON DATABASE hnk_test TO $POSTGRES_API_USER;

EOSQL
